netjson-monitoring.lua
=> [lua-monitoring] Find out ip address information of each interface #1

netjson-monitoring.lua
=> [feature] Added dhcp leases #2

netjson-monitoring.lua
* Retrieve more interfaces using the nixio library.
* Detect link local and ULA ipv6 addresses.
* Add two helpers: has_value and starts_with.
* Support --stats as the 2nd position parameter to optionally include
statistics data.
* Add the following interface data: type, up, mac, txqueuelen, mtu, speed,
bridge_members, stp, dns-search, dns-server and link-supported.
NOTE: depending on the device and openwrt version some data might not be
available
* Detect default gateway
Closes #12
TODO (I can't do more because my device doesn't provide these data):
=> [feature] Monitor addresses of all interfaces by default #12

netjson-monitoring-wan.lua, netjson-monitoring.lua
=> [lua-monitoring] Reindent lua #13

netjson-monitoring.lua
Related: https://github.com/openwisp/openwisp-monitoring/issues/182 & https://github.com/openwisp/openwisp-monitoring/pull/251.
=> [schema] Improve consistency of properties openwisp/openwisp-monitoring#182

netjson-monitoring.lua
=> [change] Switch to iwinfo to get associated clients if mesh or adhoc

netjson-monitoring.lua
=> [change] Invert rx & tx bytes on interfaces that are a part of a bridge

netjson-monitoring.lua
=> [fix] Modem-manager: do not send -- #35

CONTRIBUTING.rst, README.rst
@devkapilbansal check out these minor changes of possible problems I found while inspecting the README in the gsoc21 branch.
=> [docs] Minor improvements

openwrt-openwisp-monitoring/files/sbin/netjson-monitoring.lua, openwrt-openwisp-monitoring/tests/test_files/network_data.lua, openwrt-openwisp-monitoring/tests/test_interfaces.lua
=> [fix] Add only existing bridge members in NetJSON output #43

openwrt-openwisp-monitoring/files/monitoring.agent
=> [enhancement] Improve curl response message #50

.editorconfig, .github/workflows/ci.yml, README.rst, install-dev.sh, openwrt-openwisp-monitoring/files/monitoring.agent, openwrt-openwisp-monitoring/files/monitoring.init, qa-format, run-qa-checks, runbuild
- Added shellcheck to check the syntax of shell scripts
- Added shell formatter (shfmt) to format shell scripts
=> [qa] Add shell scripts checking and formatting

README.rst
=> [docs] Add info about verbose_mode #65

openwrt-openwisp-monitoring/files/monitoring.agent
=> [optimize] Use gzip to compress data #64

README.rst
=> [skip ci] [docs] Added instructions for installing pre-compiled packages #85

openwrt-openwisp-monitoring/files/monitoring.init
=> [fix] Fixed collect_data failing with multiple interfaces #89

openwrt-openwisp-monitoring/files/monitoring.agent, openwrt-openwisp-monitoring/files/monitoring.init
Fixed by waiting for the uuid and key to be set
Fixes #84
=> [Fix] Agent exits if device hasn't registered #84

README.rst, openwisp-monitoring/Makefile, openwisp-monitoring/files/lib/openwisp-monitoring/resources.lua, openwisp-monitoring/files/openwisp-monitoring.hotplug, openwisp-monitoring/files/sbin/netjson-monitoring.lua, qa-format, run-qa-checks
=> [enhancement] Reload agent when openwisp-config starts #97

openwisp-monitoring/files/lib/openwisp-monitoring/resources.lua, openwisp-monitoring/files/monitoring.agent, openwisp-monitoring/files/sbin/netjson-monitoring.lua
=> [fix] Discard data on bad request #101

openwisp-monitoring/Makefile, openwisp-monitoring/files/monitoring.agent, openwisp-monitoring/files/monitoring.init, openwisp-monitoring/files/netjson-monitoring
=> [change] Moved VERSION out of `/etc/openwisp/` #120

openwisp-monitoring/files/sbin/netjson-monitoring.lua, openwisp-monitoring/tests/test_files/wireless_data.lua, openwisp-monitoring/tests/test_wifi.lua
Added bitrate, quality and quality_max information for WiFi.
Closes #124
=> [feature] Added connected AP info in wireless "station" mode #124

docs/user/settings.rst
=> [qa] Fixed formatting of docs

openwisp-monitoring/files/lib/openwisp-monitoring/interfaces.lua, openwisp-monitoring/tests/test_files/interface_data.lua
=> [fix] Fixed duplicate IP address in interface
